= Querying with {sqlpp}
:description: You can query for documents in Couchbase using the {sqlpp} query language -- a language based on SQL, but designed for structured and flexible JSON documents.
:page-toclevels: 2


[abstract]
{description}



On this page we dive straight into using the Query Service API from the {name-sdk}.
For a deeper look at the concepts, to help you better understand the Query Service, and the {sqlpp} language, see the links in the <<further-information,Further Information>> section at the end of this page.


// Here we show queries against the Travel Sample collection, at cluster and scope level,
// and give links to information on adding other collections to your data.
// kafka
// postgres
// capella


== Before You Start

This page assumes that you have xref:hello-world:start-using-sdk.adoc[installed the {name-sdk}], added your IP address to the allowlist, and xref:analytics:manage:manage-nodes/create-cluster.adoc#cluster[created an Enterprise Analytics cluster].

Create a collection to work upon by xref:analytics:intro:connecting-to-data-sources.adoc#import-the-travel-sample-collections[importing the travel-sample dataset] into your cluster.



== Querying Your Dataset


[TIP]
.API Enhancements & Async
====
The {name-sdk} supports JWT and client certificate authentication, as well as a new "async" poll-based API that uses request handles to fetch results, introduced in the 2.2 release of Operational Insights Enterprise Server, and eliminating the need for long-running server connections.

The examples in this section are for the standard API, working with all 2.x releases of Operational Insights (with Server Async examples following in the <<#server-asynchronous-api,Server Async section>>).
Note, you will still be able to use this API with more recent releases of Operational Insights, in addition to the new API.
====


Execute a query and buffer all result rows in client memory:

.Scope Level
[source,csharp]
----
IQueryResult result = await scope.ExecuteQueryAsync("select 1").ConfigureAwait(false);
await foreach (var row in result.ConfigureAwait(false))
{
    Console.WriteLine("Got row: " + row.ContentAs<JsonElement>());
}
----

.Cluster Level
[source,csharp]
----
IQueryResult result = await cluster.ExecuteQueryAsync("select 1").ConfigureAwait(false);
await foreach (var row in result.ConfigureAwait(false))
{
    Console.WriteLine("Got row: " + row.ContentAs<JsonElement>());
}
----


=== Positional and Named Parameters

Supplying parameters as individual arguments to the query allows the query engine to optimize the parsing and planning of the query. You can either supply these parameters by name or by position.

Execute a streaming query with positional arguments:

.Positional Parameters
[source,csharp]
----
var result = await cluster.ExecuteQueryAsync("select ?=1", options => options.WithPositionalParameter(1)).ConfigureAwait(false);
await foreach (var row in result.ConfigureAwait(false))
{
    Console.WriteLine("Got row: " + row.ContentAs<JsonElement>());
}
----

Execute a streaming query with named arguments:

.Named Parameters
[source,csharp]
----
var result = await cluster.ExecuteQueryAsync("select $foo=1", options => options.WithNamedParameter("foo", 1)).ConfigureAwait(false);
await foreach (var row in result.ConfigureAwait(false))
{
    Console.WriteLine("Got row: " + row.ContentAs<JsonElement>());
}
----

WARNING: Helper methods `WithNamedParameter` and `WithPositionalParameter` take 1 parameter, and add it to the existing collection in the options. The methods `WithNamedParameters` and `WithPositionalParameters` (note the plural) take a collection of parameters, and replace all the parameters in the existing collection.



== Server Asynchronous API

In the 2.2 release, the Operational Insights Server added an asynchronous request API.
The SDK will send a request, poll for results, and then fetch once the result is available.
The SDK supports each stage of this information flow:

`cluster.StartQueryAsync()` → `QueryHandle` → `QueryStatus` → `QueryResultsHandle`


.Server Asynchronous API Example
[source,csharp]
----
include::devguide:example$dotnet/ServerAsync.cs[indent=0,tag=server-async]
----



== Query Options

The query service provides an array of options to customize your query.
The following table lists them all:

.Available Query Options
[options="header"]
|====
| Name       | Description
| `bool AsStreaming { get; init; }` | If true, the IQueryResult will be returned as a streaming result.
| `string ClientContextId { get; init; }` | The `ClientContextId` to be used for the query request. Used to identify the query in logs and profiles. If none is provided, a new GUID will be generated.
| `IDeserializer? Deserializer { get; init; }` | Used to deserialize query rows. Default to `StjJsonDeserializer`
| `Dictionary<string, object> NamedParameters { get; init; }` | Named parameters for the query request. Use `WithNamedParameters(Dictionary<string, object>)` or `WithNamedParameter(string, object)` to create updated copies.
| `List<object> PositionalParameters { get; init; }` | Positional parameters for the query request. Use `WithPositionalParameters(IEnumerable<object>)` or `WithPositionalParameter(object)` to create updated copies.
| `Dictionary<string, object> Raw { get; init; }` | Raw parameters passed directly to the analytics service for advanced options. Use `WithRawParameters(Dictionary<string, object>)` or `WithRaw(string, object)` to create updated copies.
| `bool? ReadOnly { get; init; }` | Specifies that this query should be executed in read-only mode, disabling the ability for the query to make any changes to the data.
| `QueryScanConsistency? ScanConsistency { get; init; }` | The scan consistency for the query request.
| `TimeSpan? Timeout { get; init; }` | Sets the overall timeout for the query request. If unset, the default `TimeoutOptions`'s `QueryTimeout` will be used. Note that if a `CancellationToken` is used on the query call, it may trigger before this timeout.
|====



== Further Information

The xref:analytics:sqlpp:1_intro.adoc[{sqlpp} for Analytics Reference]
offers a complete guide to the {sqlpp} language for both of our analytics (Insights) services, including all of the latest additions.
