= Deployment
:page-toclevels: 2
:description: Transition from dev environment to prod, and keep up with the latest fixes.
// :page-aliases: sdk-release-notes.adoc


// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at wwww.

[abstract]
{description}





One of Couchbase's strengths is speedy response, so deployment of apps should be in the same region as your Enterprise Analytics cluster.

We always recommend the xref::operational-insights-sdk-release-notes.adoc#latest-release[latest version] of the SDK. 
This not only contains the latest security updates and bug fixes, but will be compatible with the latest Operational Insights release.
//  -- Capella always runs a recent version of Operational Insights.


TIP: Connecting to a xref:analytics:intro:intro.adoc[Operational Insights _Capella_] cluster from .NET is not currently possible.


Before deploying, take note of any xref:compatibility.adoc[compatibility] issues for the language platform and underlying OS.
The xref:sdk-full-installation.adoc[full installation guide] should cover any special cases for all supported environments.


== Development & Testing Environments

During development, some shortcuts are taken to get up and running which would not be acceptable during deployment.
These include use of administrator permissions, connecting from your laptop instead of a secure app server, and even disabling certificate verification for TLS.
Testing environments may also differ from deployment.

The {name-sdk} docs note whenever a shortcut is being taken, but here is a non-exhaustive list of those development practices which should not be carried over to production deployments:

* Over-priveleged access
* Geographical separation of app server and database
* Skipping certificate verification
// * more

The best way to accommodate developing an application that is to be deployed to production is to use the platform's default approach for configuration files.

For the .NET Analytics SDK, that is to keep a separate properties file for your development and production environments.



////
== Further Reading

* Integrate Couchbase with your data ecosystem:
** xref:project-docs:third-party-integrations.adoc[SDK Integrations]
** xref:server:develop:integrations.adoc[Integrations across Couchbase]
* xref:project-docs:get-involved.adoc[Contribute to the SDK] 
////

